//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTEinkToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XTEinkToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 《鹿舞起源》
        ///　　那一刻，殘陽如血，落日的餘暉透過鑲了金邊的晚霞，斜射在滿地青苔的原野上。抽了穗的芒草猶如一團團跳動的白色火焰，與萬道霞光交相輝映。我累得躺在這片天地之間，沙沙的風在我耳邊輕聲慢語，娓娓訴說著北山原野上鹿舞的真正精髓。
        ///　　當那裡還是一片荒蕪、到處都是齊身高的野草和黑壓壓的森林的時候，嘉十就隨著爺爺從北上川的東面搬了過來，開墾了一小塊農田，每日靠種植小米和稗子為生。
        ///　　一天，嘉十不小心從栗子樹上摔了下來，傷了左腿的膝蓋。在當地，人們凡是遇上這種事兒，都會去西山的溫泉那裡，搭個帳篷住下來療傷。
        ///　　於是在一個天氣晴朗的日子裡，嘉十也背上乾糧、豆醬和鍋出門了。他拖著受了傷的腿，一瘸一拐，步履蹣跚地走過了那片吐著銀白色穗子的芒草地。
        ///　　也不知跨過了多少條小溪，翻過了多少塊岩石，當連綿巍峨的山巒豁然呈現在眼前，山上的樹木棵棵猶如衫苔般涇渭分明時，西斜的太陽赫然高懸在了十株蔥郁的赤楊樹上空，投射出耀眼的光芒。
        ///　　嘉十來到一塊草地上，卸下了肩頭的包袱，取出一個由七葉樹籽和穀子製成的飯團吃了起來。草原上，星羅棋佈的芒草連綿成片，隨風泛起的白色波浪一眼望不到邊際。嘉十一邊吃著飯團，一邊欣賞著 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string previewTestTC {
            get {
                return ResourceManager.GetString("previewTestTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 《小意达的花儿》
        ///　　“我可怜的花朵现在全死了！”小依达说，“它们昨天晚上还那么美丽，可现在连叶子都失去了生机。为什么会这样呢？”她问一个坐在沙发上的学生，因为她很喜欢他。他可以讲出最美好的故事，可以剪出最神奇的图案：各种花朵的图案，大门能够开启的城堡的图案，还有小姑娘在里面跳舞的心的图案。他是一个快活的学生。“为什么花朵今天垂头丧气的？”她又问了一遍，把一捧已经枯萎的花束指给他看。
        ///　　“你知道它们都做了什么吗？”学生说，“这些花儿昨天参加了整晚的舞会，所以今天才没精打采的。”
        ///　　“可是花儿不会跳舞！”小依达说。
        ///　　“它们会跳，”学生说，“当夜幕降临，我们都睡熟了的时候，它们就开心地聚在一起，几乎每个晚上都要开舞会。”
        ///　　“小花儿也可以参加舞会吗？”
        ///　　“当然可以，”学生说，“小雏菊和山谷百合都可以参加。”
        ///　　“那些最漂亮的花在什么地方跳舞呢？”小依达问。
        ///　　“你去过城外的大宫殿吗？国王夏天就住在那儿，宫殿里有最美的花园，那里开满了花朵。你见过那些天鹅吗？当你要给它们面包屑的时候，它们就会游过来。相信我，花朵们就是在那里举行舞会的。”
        ///　　“我和妈妈去过那里，就在昨天，”小依达 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string previewTexts {
            get {
                return ResourceManager.GetString("previewTexts", resourceCulture);
            }
        }
    }
}
