//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTEinkToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XTEinkToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 他伫立在基督像前，耶稣的双手里放满了精致的金质器皿以及圣杯。珠宝装饰的神坛上，蜡烛十分明亮，一缕青烟，直升上圆圆的屋顶。他开始叩头祈祷，那些穿着华服的教士走下祭坛，让开了。
        ///突然街上传来一阵喧哗，许多贵族，头上插着羽毛，拖着刺刀，有的更拿着钢制的盾牌，一齐走了进来。他们叫着：“做梦的家伙在哪儿？穿得像乞丐的国王在哪儿？羞辱我们国家的人在哪儿？我们要杀了他，他没有资格统治我们。”
        ///少年王又叩头祷告，祷告完毕，才站起身来，很忧愁地看着他们。
        ///看啦，就在这时，一缕阳光从贴满彩色花边的窗口射进来照在他身上，犹如穿上了一件金丝王袍，比订制的那件还要尊贵得多。水仙的枯木枝也开满了鲜花，朵朵比珍珠还洁白。玫瑰干枯的荆棘也开了花，朵朵比红玉还艳红。比珍珠还白的是那些水仙花朵，花梗犹如光亮的银子；比红玉还红的是那些玫瑰，花叶犹如金叶片片。
        ///他穿着王袍站在那儿，神坛的门打开了，供台上的水晶突然射来一束神秘的亮光。他穿着王袍站在那儿，上帝的荣光照满各处，圣像在雕刻的壁龛里蠕动。他穿着王袍站在他们面前，风琴传出了音乐，号手吹起号来，歌手也唱歌了。
        ///人民全部敬畏地跪下，贵族连忙插好刺刀，行了臣服之礼。主教的脸也苍白了，手也战 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string previewTexts {
            get {
                return ResourceManager.GetString("previewTexts", resourceCulture);
            }
        }
    }
}
