//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTEinkToolkit {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmMainCodeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmMainCodeString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XTEinkToolkit.FrmMainCodeString", typeof(FrmMainCodeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 查看预览 的本地化字符串。
        /// </summary>
        internal static string abcBtnPreviewText {
            get {
                return ResourceManager.GetString("abcBtnPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中国智造，惠及全球ABCabc123 的本地化字符串。
        /// </summary>
        internal static string abcFontPreviewText {
            get {
                return ResourceManager.GetString("abcFontPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择字体文件（可多选） 的本地化字符串。
        /// </summary>
        internal static string abcOpenFontDialogTitle {
            get {
                return ResourceManager.GetString("abcOpenFontDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择的字体文件中不包含任何有效的字形。 的本地化字符串。
        /// </summary>
        internal static string abcOpenFontNoFamily {
            get {
                return ResourceManager.GetString("abcOpenFontNoFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrueType 字体文件 的本地化字符串。
        /// </summary>
        internal static string abcOpenFontTypeName {
            get {
                return ResourceManager.GetString("abcOpenFontTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染字体时发生错误 的本地化字符串。
        /// </summary>
        internal static string abcRenderingError {
            get {
                return ResourceManager.GetString("abcRenderingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在渲染字体... 的本地化字符串。
        /// </summary>
        internal static string abcRenderingFont {
            get {
                return ResourceManager.GetString("abcRenderingFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染中... 的本地化字符串。
        /// </summary>
        internal static string abcRenderingPreview {
            get {
                return ResourceManager.GetString("abcRenderingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BIN字体文件 的本地化字符串。
        /// </summary>
        internal static string abcSaveDialogTypeName {
            get {
                return ResourceManager.GetString("abcSaveDialogTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体文件导出成功！ 的本地化字符串。
        /// </summary>
        internal static string abcSuccessDialogMsg {
            get {
                return ResourceManager.GetString("abcSuccessDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出完成 的本地化字符串。
        /// </summary>
        internal static string abcSuccessDialogTitle {
            get {
                return ResourceManager.GetString("abcSuccessDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 false 的本地化字符串。
        /// </summary>
        internal static string boolShowTCPreview {
            get {
                return ResourceManager.GetString("boolShowTCPreview", resourceCulture);
            }
        }
    }
}
